<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Messages [
  <!ELEMENT Messages (Package*)>

  <!ELEMENT Package (Error*)>
  <!ATTLIST Package ID CDATA #REQUIRED>
  <!ATTLIST Package DefaultComponent CDATA #REQUIRED>

  <!ELEMENT Error (#PCDATA)>
  <!ATTLIST Error Key ID #REQUIRED>
  <!ATTLIST Error Component CDATA #IMPLIED>
  <!ATTLIST Error NativeErrorCode CDATA #REQUIRED>
  <!ATTLIST Error Params CDATA "0">
]>

<Messages>
      <Package ID="8" DefaultComponent="SimbaClient">

      <!-- Error thrown when memory allocation failed.  --> 
      <Error Key="ClientMemAllocErr" NativeErrorCode="1">Memory allocation error.</Error>

      <!-- Error thrown when cannot find custom property. --> 
      <Error Key="ClientCustomPropNotFound" NativeErrorCode="5">Custom property not found.</Error>

      <!-- Error thrown when attempt to execute connection required command while no connection exists. --> 
      <Error Key="ClientConnNotEst" NativeErrorCode="14">Current operation requires established connection but no connection has been established yet.</Error>

      <!-- Error thrown when attempt to execute connection required command while no connection exists. --> 
      <Error Key="ClientOperationNotSupported" NativeErrorCode="15">Current operation not supported.</Error>

      <!-- Error thrown when SQL type is not supported by the driver. --> 
      <Error Key="ClientSQLTypeNotSupported" NativeErrorCode="16">SQL data type not supported.</Error>

      <!-- Error thrown when communication link error. --> 
      <Error Key="ClientCommLinkErr" NativeErrorCode="17">Error occurred during communication with the server.</Error>

      <!-- Error thrown when the reponse list is empty. --> 
      <Error Key="ClientEmptyResponse" NativeErrorCode="19">Empty response returned by the server.</Error>

      <!-- Error thrown When the server return BKPProtoErr. --> 
      <Error Key="ClientServerEndBKPProtoErr" Params="1" NativeErrorCode="20">BKPProtoErr returned by the server: %1%.</Error>

      <!-- Error thrown When the server returned different message id. -->
      <Error Key="ClientMessageIDMismatched" NativeErrorCode="21">The server returned an invalid message ID.</Error>

      <!-- Error thrown when the server returned invalid or malformed keys in an RKPUnauth. -->
      <Error Key="ClientInvalidLoginAttrs" NativeErrorCode="22">Malformed connection attribute data requested by server.</Error>

      <!-- Error thrown when there was an error serializing messages to send to the server. -->
      <Error Key="ClientSerializationErr" NativeErrorCode="23">An error occurred while marshalling data for the network.</Error>

      <!-- Error thrown when there was an error deserializing messages from the server. -->
      <Error Key="ClientDeserializationErr" NativeErrorCode="23">An error occurred while demarshalling data from the network.</Error>

      <!-- Error thrown when the client recieves a response that is not valid for the corresponding request. -->
      <Error Key="ClientInvalidResponse" NativeErrorCode="25">The server returned a response that is not valid for the corresponding request.</Error>

      <!-- Error thrown when the pre-action of the sending process failed. -->
      <Error Key="ClientPreActionErr" NativeErrorCode="26">An error occurred prior sending the message to the server.</Error>

      <!-- Error thrown if two servers with different endianness are managed by the same CommManager. -->
      <Error Key="ClientServerEndianConflict" NativeErrorCode="27">The endianness of the connected server is not compatible.</Error>

      <!-- Error thrown when attempting to access an invalid column number. --> 
      <Error Key="ClientInvalidColumnNumber" NativeErrorCode="28">Invalid column number.</Error>

      <!-- Error thrown when an invalid column status is read. --> 
      <Error Key="ClientInvalidColumnStatus" NativeErrorCode="29">Invalid column status.</Error>

      <!-- Error thrown when no Servers are specified -->
      <Error Key="ClientNoServers" NativeErrorCode="30">No servers specified in configuration.</Error>

      <!-- Error thrown when a connection already exists and another is being made. -->
      <Error Key="ClientConnAlreadyExist" NativeErrorCode="31">An error occurred due to attempting to connect while already connected.</Error>

      <!-- Error thrown when the server sends an RKPError with no diagnostics -->
      <Error Key="ClientUnknownServerError" NativeErrorCode="33">Unknown error from server.</Error>

      <!-- Error thrown when executing with a paramset size > 32bit -->
      <Error Key="ParamsetCountTooLarge" NativeErrorCode="34">64 bit paramset count not supported.</Error>

      <!-- Warning posted when log file can't be opened -->
      <Error Key="FailedToOpenLogFile" Params="1" NativeErrorCode="35">Failed to open log file for writing: %1%.</Error>

      <!-- Error thrown when numeric/datetime pushed param data cant be converted for sending to server -->
      <Error Key="ErrorConvertingPushedParamData" NativeErrorCode="36">The pushed param data could not be converted to send to the server.</Error>

      <!-- Error thrown when the server sends an RKPError with no diagnostics -->
      <Error Key="ConnectionRefused" NativeErrorCode="37">Server refused connection; check configuration (server ip, server port, use ssl, ssl certificate/key files).</Error>

      <!-- Error thrown when an unknown error occurs during set connection attribute -->
      <Error Key="SetConnectionAttributeError" NativeErrorCode="38">Failed to set connection attribute.</Error>

      <!-- Error thrown when an unknown error occurs during set statement attribute -->
      <Error Key="SetStatementAttributeError" NativeErrorCode="39">Failed to set statement attribute.</Error>

      <!-- Error thrown when an application attempts a  -->
      <Error Key="ClientNotConnected" NativeErrorCode="40">Client is not connected; request denied.</Error>

      <!-- Error thrown when parameter bindings don't match the metadata. -->
      <Error Key="InvalidParameterBindings" NativeErrorCode="41">Invalid parameter bindings.</Error>

      <!-- Error thrown when the client has an internal error. -->
      <Error Key="ClientInternalError" NativeErrorCode="42">Internal Client Error.</Error>

      <!-- Error thrown when an error is returned for a column in a data set. -->
      <Error Key="ClientColumnDataError" NativeErrorCode="44">Error retrieving data for column: %1%.</Error>

      <!-- Error thrown when the connection timeout has been reached. -->
      <Error Key="ConnectionTimeout" NativeErrorCode="50">The timeout has been reached before a response from the server was received.</Error>

      <!-- Error thrown when the connection to the server has been terminated. -->
      <Error Key="ConnectionDead" NativeErrorCode="51">The connection to the server has been terminated.</Error>

          <!-- Error thrown when the client server handshake fails. -->
      <Error Key="ClientServerHandshakeFailed" NativeErrorCode="60">Could not establish a connection to the server.  Check with your vendor to determine whether SSL is enabled on the server.  Your client 'UseSsl' value must match that of the server.</Error>
        
      <!-- Error thrown execution is cancelled on the client. -->
      <Error Key="ExecutionCanceled" NativeErrorCode="61">Execution canceled.</Error>
        
      <!-- Error thrown when the client cannot establish a connection. -->
      <Error Key="ClientCannotConnect" NativeErrorCode="62">Client cannot establish a connection to the server.</Error>

      <!-- Error thrown when the client cannot parse the SERVERS connection keyword.. -->
      <Error Key="ClientErrorParsingServers" Params="1" NativeErrorCode="63">Error parsing SERVERS connection key. Invalid value: %1%</Error>

      <!-- Warning used when attempting to login after integrated security authentication failed. -->
      <Error Key="AttempingLoginWithoutItegratedSecurity" NativeErrorCode="64">Attempting to login without integrated security.</Error>

      <!-- Warning used when the client tries to use integrated security but the server doesn't support it. -->
      <Error Key="ServerNoIntegratedSecuritySupport" NativeErrorCode="65">The server does not support integrated security.</Error>

      <!-- Error used when the SPN for integrated security is missing. -->
      <Error Key="IntegratedSecuritySPNMissing" NativeErrorCode="66" Params="1">Required key for integrated security: "%1%" is missing.</Error>

      <!-- Error thrown when there was an error loading the connection dialog DLL. -->
      <Error Key="ClientDialogLoadErr" Params="1" NativeErrorCode="67">An error occurred while attempting to load the connection dialog DLL: %1%</Error>

      <!-- Error thrown when there was an error loading the dialog function from the DLL. -->
      <Error Key="ClientDialogFuncErr" Params="1" NativeErrorCode="68">An error occurred while attempting to load the dialog function: %1%</Error>

      <!-- Error used when credentials aren't available for integrted security. -->
      <Error Key="ClientConnNoCredentials" NativeErrorCode="69">No credentials are available for establishing integrated security.</Error>

      <!-- Error thrown when the connection to the server has been terminated on the first message (handshake). -->
      <Error Key="ConnectionDeadFirstMessage" NativeErrorCode="70">The connection to the server has been terminated while connecting. Check server version and/or SSL configuration for compatibility.</Error>
    </Package>
</Messages>
